import { Equipment } from "src/domain/model/Equipment"
import { CastAny } from "src/types/tsUtils"

// TODO to prod
const host =
  "https://raw.githubusercontent.com/arx-8/cocorosekai-equipment-customizer/feature/prototype/src/assets/equipments/"
// const host =
//   "https://raw.githubusercontent.com/arx-8/cocorosekai-equipment-customizer/master/src/assets/equipments/"

export const data: Equipment[] = [
  {
    id: 1,
    name: "羊飼いの杖",
    rawName: "羊飼いの杖",
    attribute: "light",
    statuses: {
      hp: 72,
      magicAtk: 43,
      magicDef: 0,
      physicalAtk: 14,
      physicalDef: 0,
    },
    imageUrl: host + "70.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ5%軽減",
      },
    ],
  },
  {
    id: 2,
    name: "ヴィブロブレード",
    rawName: "ヴィブロブレード",
    attribute: "void",
    statuses: {
      hp: 30,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 48,
      physicalDef: 0,
    },
    imageUrl: host + "71.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 3,
    name: "デスサイズ",
    rawName: "デスサイズ",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 12,
      magicDef: 0,
      physicalAtk: 48,
      physicalDef: 0,
    },
    imageUrl: host + "72.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 4,
    name: "パペットシアター",
    rawName: "パペットシアター",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 48,
      magicDef: 0,
      physicalAtk: 12,
      physicalDef: 0,
    },
    imageUrl: host + "73.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 5,
    name: "ヴィブロブレード",
    rawName: "ヴィブロブレード+",
    attribute: "void",
    statuses: {
      hp: 60,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 96,
      physicalDef: 0,
    },
    imageUrl: host + "74.jpg",
    enhancementsNum: 1,
    equipCost: 15,
    specialEffects: [],
  },
  {
    id: 6,
    name: "デスサイズ",
    rawName: "デスサイズ+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 24,
      magicDef: 0,
      physicalAtk: 96,
      physicalDef: 0,
    },
    imageUrl: host + "75.jpg",
    enhancementsNum: 1,
    equipCost: 15,
    specialEffects: [],
  },
  {
    id: 7,
    name: "パペットシアター",
    rawName: "パペットシアター+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 96,
      magicDef: 0,
      physicalAtk: 24,
      physicalDef: 0,
    },
    imageUrl: host + "76.jpg",
    enhancementsNum: 1,
    equipCost: 15,
    specialEffects: [],
  },
  {
    id: 8,
    name: "ヴィブロブレード",
    rawName: "ヴィブロブレード++",
    attribute: "void",
    statuses: {
      hp: 90,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 144,
      physicalDef: 0,
    },
    imageUrl: host + "77.jpg",
    enhancementsNum: 2,
    equipCost: 20,
    specialEffects: [],
  },
  {
    id: 9,
    name: "デスサイズ",
    rawName: "デスサイズ++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 36,
      magicDef: 0,
      physicalAtk: 144,
      physicalDef: 0,
    },
    imageUrl: host + "78.jpg",
    enhancementsNum: 2,
    equipCost: 20,
    specialEffects: [],
  },
  {
    id: 10,
    name: "パペットシアター",
    rawName: "パペットシアター++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 144,
      magicDef: 0,
      physicalAtk: 36,
      physicalDef: 0,
    },
    imageUrl: host + "79.jpg",
    enhancementsNum: 2,
    equipCost: 20,
    specialEffects: [],
  },
  {
    id: 11,
    name: "羊飼いの杖",
    rawName: "羊飼いの杖+",
    attribute: "light",
    statuses: {
      hp: 146,
      magicAtk: 88,
      magicDef: 0,
      physicalAtk: 29,
      physicalDef: 0,
    },
    imageUrl: host + "80.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ7%軽減",
      },
    ],
  },
  {
    id: 12,
    name: "羊飼いの杖",
    rawName: "羊飼いの杖++",
    attribute: "light",
    statuses: {
      hp: 222,
      magicAtk: 133,
      magicDef: 0,
      physicalAtk: 44,
      physicalDef: 0,
    },
    imageUrl: host + "81.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ10%軽減",
      },
    ],
  },
  {
    id: 13,
    name: "ウィングスタッフ",
    rawName: "ウィングスタッフ",
    attribute: "wind",
    statuses: {
      hp: 0,
      magicAtk: 58,
      magicDef: 0,
      physicalAtk: 14,
      physicalDef: 0,
    },
    imageUrl: host + "82.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "眠り無効化確率+40%",
      },
    ],
  },
  {
    id: 14,
    name: "ウィングスタッフ",
    rawName: "ウィングスタッフ+",
    attribute: "wind",
    statuses: {
      hp: 0,
      magicAtk: 117,
      magicDef: 0,
      physicalAtk: 29,
      physicalDef: 0,
    },
    imageUrl: host + "83.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "眠り無効化確率+60%",
      },
    ],
  },
  {
    id: 15,
    name: "ウィングスタッフ",
    rawName: "ウィングスタッフ++",
    attribute: "wind",
    statuses: {
      hp: 0,
      magicAtk: 178,
      magicDef: 0,
      physicalAtk: 44,
      physicalDef: 0,
    },
    imageUrl: host + "84.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "眠り無効化確率+80%",
      },
    ],
  },
  {
    id: 16,
    name: "ブルームゲート",
    rawName: "ブルームゲート",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 48,
      magicDef: 0,
      physicalAtk: 12,
      physicalDef: 0,
    },
    imageUrl: host + "85.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "眠り無効化確率+30%",
      },
    ],
  },
  {
    id: 17,
    name: "ブルームゲート",
    rawName: "ブルームゲート+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 98,
      magicDef: 0,
      physicalAtk: 24,
      physicalDef: 0,
    },
    imageUrl: host + "86.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "眠り無効化確率+45%",
      },
    ],
  },
  {
    id: 18,
    name: "ブルームゲート",
    rawName: "ブルームゲート++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 148,
      magicDef: 0,
      physicalAtk: 37,
      physicalDef: 0,
    },
    imageUrl: host + "87.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "眠り無効化確率+60%",
      },
    ],
  },
  {
    id: 19,
    name: "アイスソード",
    rawName: "アイスソード",
    attribute: "water",
    statuses: {
      hp: 72,
      magicAtk: 14,
      magicDef: 0,
      physicalAtk: 43,
      physicalDef: 0,
    },
    imageUrl: host + "88.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "受ける物理ダメージを5%軽減",
      },
    ],
  },
  {
    id: 20,
    name: "アイスソード",
    rawName: "アイスソード+",
    attribute: "water",
    statuses: {
      hp: 146,
      magicAtk: 29,
      magicDef: 0,
      physicalAtk: 88,
      physicalDef: 0,
    },
    imageUrl: host + "89.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "受ける物理ダメージを7%軽減",
      },
    ],
  },
  {
    id: 21,
    name: "アイスソード",
    rawName: "アイスソード++",
    attribute: "water",
    statuses: {
      hp: 222,
      magicAtk: 44,
      magicDef: 0,
      physicalAtk: 133,
      physicalDef: 0,
    },
    imageUrl: host + "90.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "受ける物理ダメージを10%軽減",
      },
    ],
  },
  {
    id: 22,
    name: "ライトガントレット",
    rawName: "ライトガントレット",
    attribute: "void",
    statuses: {
      hp: 60,
      magicAtk: 12,
      magicDef: 0,
      physicalAtk: 36,
      physicalDef: 0,
    },
    imageUrl: host + "91.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "受ける物理ダメージを5%軽減",
      },
    ],
  },
  {
    id: 23,
    name: "ライトガントレット",
    rawName: "ライトガントレット+",
    attribute: "void",
    statuses: {
      hp: 122,
      magicAtk: 24,
      magicDef: 0,
      physicalAtk: 73,
      physicalDef: 0,
    },
    imageUrl: host + "92.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "受ける物理ダメージを7%軽減",
      },
    ],
  },
  {
    id: 24,
    name: "ライトガントレット",
    rawName: "ライトガントレット++",
    attribute: "void",
    statuses: {
      hp: 185,
      magicAtk: 37,
      magicDef: 0,
      physicalAtk: 111,
      physicalDef: 0,
    },
    imageUrl: host + "93.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "受ける物理ダメージを10%軽減",
      },
    ],
  },
  {
    id: 25,
    name: "ウールステッキ",
    rawName: "ウールステッキ",
    attribute: "void",
    statuses: {
      hp: 60,
      magicAtk: 36,
      magicDef: 0,
      physicalAtk: 12,
      physicalDef: 0,
    },
    imageUrl: host + "94.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ5%軽減",
      },
    ],
  },
  {
    id: 26,
    name: "ウールステッキ",
    rawName: "ウールステッキ+",
    attribute: "void",
    statuses: {
      hp: 122,
      magicAtk: 73,
      magicDef: 0,
      physicalAtk: 24,
      physicalDef: 0,
    },
    imageUrl: host + "95.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ7%軽減",
      },
    ],
  },
  {
    id: 27,
    name: "ウールステッキ",
    rawName: "ウールステッキ++",
    attribute: "void",
    statuses: {
      hp: 185,
      magicAtk: 111,
      magicDef: 0,
      physicalAtk: 37,
      physicalDef: 0,
    },
    imageUrl: host + "96.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ10%軽減",
      },
    ],
  },
  {
    id: 28,
    name: "宵闇の書",
    rawName: "宵闇の書",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 135,
      magicDef: 100,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "97.jpg",
    enhancementsNum: 0,
    equipCost: 30,
    specialEffects: [],
  },
  {
    id: 29,
    name: "ラピッドスクゥアー",
    rawName: "ラピッドスクゥアー",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 35,
      physicalDef: 0,
    },
    imageUrl: host + "100.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [
      {
        rawText: "クリティカル+5%",
      },
    ],
  },
  {
    id: 30,
    name: "ラピッドスクゥアー",
    rawName: "ラピッドスクゥアー+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 70,
      physicalDef: 0,
    },
    imageUrl: host + "101.jpg",
    enhancementsNum: 1,
    equipCost: 19,
    specialEffects: [
      {
        rawText: "クリティカル+10%",
      },
    ],
  },
  {
    id: 31,
    name: "ラピッドスクゥアー",
    rawName: "ラピッドスクゥアー++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 105,
      physicalDef: 0,
    },
    imageUrl: host + "102.jpg",
    enhancementsNum: 2,
    equipCost: 28,
    specialEffects: [
      {
        rawText: "クリティカル+15%",
      },
    ],
  },
  {
    id: 32,
    name: "劫火ノ槍",
    rawName: "劫火ノ槍",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 135,
      physicalDef: 100,
    },
    imageUrl: host + "103.jpg",
    enhancementsNum: 0,
    equipCost: 30,
    specialEffects: [],
  },
  {
    id: 33,
    name: "劫火ノ槍",
    rawName: "劫火ノ槍+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 203,
      physicalDef: 150,
    },
    imageUrl: host + "104.jpg",
    enhancementsNum: 1,
    equipCost: 45,
    specialEffects: [],
  },
  {
    id: 34,
    name: "クリスタルリーパー",
    rawName: "クリスタルリーパー",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 54,
      physicalDef: 0,
    },
    imageUrl: host + "106.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 35,
    name: "クリスタルリーパー",
    rawName: "クリスタルリーパー+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 108,
      physicalDef: 0,
    },
    imageUrl: host + "107.jpg",
    enhancementsNum: 1,
    equipCost: 15,
    specialEffects: [],
  },
  {
    id: 36,
    name: "クリスタルリーパー",
    rawName: "クリスタルリーパー++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 162,
      physicalDef: 0,
    },
    imageUrl: host + "108.jpg",
    enhancementsNum: 2,
    equipCost: 20,
    specialEffects: [],
  },
  {
    id: 37,
    name: "水晶の杖",
    rawName: "水晶の杖",
    attribute: "fire",
    statuses: {
      hp: 66,
      magicAtk: 44,
      magicDef: 0,
      physicalAtk: 13,
      physicalDef: 0,
    },
    imageUrl: host + "109.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+40%",
      },
    ],
  },
  {
    id: 38,
    name: "水晶の杖",
    rawName: "水晶の杖+",
    attribute: "fire",
    statuses: {
      hp: 140,
      magicAtk: 91,
      magicDef: 0,
      physicalAtk: 28,
      physicalDef: 0,
    },
    imageUrl: host + "110.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+60%",
      },
    ],
  },
  {
    id: 39,
    name: "水晶の杖",
    rawName: "水晶の杖++",
    attribute: "fire",
    statuses: {
      hp: 204,
      magicAtk: 137,
      magicDef: 0,
      physicalAtk: 42,
      physicalDef: 0,
    },
    imageUrl: host + "111.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+80%",
      },
    ],
  },
  {
    id: 40,
    name: "クラックゲート",
    rawName: "クラックゲート",
    attribute: "void",
    statuses: {
      hp: 54,
      magicAtk: 37,
      magicDef: 0,
      physicalAtk: 11,
      physicalDef: 0,
    },
    imageUrl: host + "112.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+30%",
      },
    ],
  },
  {
    id: 41,
    name: "クラックゲート",
    rawName: "クラックゲート+",
    attribute: "void",
    statuses: {
      hp: 116,
      magicAtk: 76,
      magicDef: 0,
      physicalAtk: 23,
      physicalDef: 0,
    },
    imageUrl: host + "113.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+45%",
      },
    ],
  },
  {
    id: 42,
    name: "クラックゲート",
    rawName: "クラックゲート++",
    attribute: "void",
    statuses: {
      hp: 167,
      magicAtk: 115,
      magicDef: 0,
      physicalAtk: 35,
      physicalDef: 0,
    },
    imageUrl: host + "114.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+60%",
      },
    ],
  },
  {
    id: 43,
    name: "パラレルパラソル",
    rawName: "パラレルパラソル",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 35,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "115.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [
      {
        rawText: "クリティカル率+5%",
      },
    ],
  },
  {
    id: 44,
    name: "パラレルパラソル",
    rawName: "パラレルパラソル+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 70,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "116.jpg",
    enhancementsNum: 1,
    equipCost: 19,
    specialEffects: [
      {
        rawText: "クリティカル率+10%",
      },
    ],
  },
  {
    id: 45,
    name: "パラレルパラソル",
    rawName: "パラレルパラソル++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 105,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "117.jpg",
    enhancementsNum: 2,
    equipCost: 28,
    specialEffects: [
      {
        rawText: "クリティカル率+15%",
      },
    ],
  },
  {
    id: 46,
    name: "サンライトショット",
    rawName: "サンライトショット",
    attribute: "light",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 70,
      physicalDef: 0,
    },
    imageUrl: host + "118.jpg",
    enhancementsNum: 0,
    equipCost: 13,
    specialEffects: [
      {
        rawText: "クリティカル率+10%",
      },
    ],
  },
  {
    id: 47,
    name: "サンライトショット",
    rawName: "サンライトショット+",
    attribute: "light",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 125,
      physicalDef: 0,
    },
    imageUrl: host + "119.jpg",
    enhancementsNum: 1,
    equipCost: 23,
    specialEffects: [
      {
        rawText: "クリティカル率+15%",
      },
    ],
  },
  {
    id: 48,
    name: "サンライトショット",
    rawName: "サンライトショット++",
    attribute: "light",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 180,
      physicalDef: 0,
    },
    imageUrl: host + "120.jpg",
    enhancementsNum: 2,
    equipCost: 33,
    specialEffects: [
      {
        rawText: "クリティカル率+20%",
      },
    ],
  },
  {
    id: 49,
    name: "凶眼の竜玉",
    rawName: "凶眼の竜玉",
    attribute: "void",
    statuses: {
      hp: 200,
      magicAtk: 80,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "121.jpg",
    enhancementsNum: 0,
    equipCost: 22,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージ+10%",
      },
    ],
  },
  {
    id: 50,
    name: "凶眼の竜玉",
    rawName: "凶眼の竜玉+",
    attribute: "void",
    statuses: {
      hp: 400,
      magicAtk: 150,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "122.jpg",
    enhancementsNum: 1,
    equipCost: 42,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージ+20%",
      },
    ],
  },
  {
    id: 51,
    name: "凶眼の竜玉",
    rawName: "凶眼の竜玉++",
    attribute: "void",
    statuses: {
      hp: 600,
      magicAtk: 220,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "123.jpg",
    enhancementsNum: 2,
    equipCost: 62,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージ+30%",
      },
    ],
  },
  {
    id: 52,
    name: "無極の手甲",
    rawName: "無極の手甲",
    attribute: "void",
    statuses: {
      hp: 220,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 85,
      physicalDef: 0,
    },
    imageUrl: host + "124.jpg",
    enhancementsNum: 0,
    equipCost: 24,
    specialEffects: [
      {
        rawText: "ブロック率が15%上昇する",
      },
    ],
  },
  {
    id: 53,
    name: "無極の手甲",
    rawName: "無極の手甲+",
    attribute: "void",
    statuses: {
      hp: 420,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 155,
      physicalDef: 0,
    },
    imageUrl: host + "125.jpg",
    enhancementsNum: 1,
    equipCost: 44,
    specialEffects: [
      {
        rawText: "ブロック率が27%上昇する",
      },
    ],
  },
  {
    id: 54,
    name: "無極の手甲",
    rawName: "無極の手甲++",
    attribute: "void",
    statuses: {
      hp: 620,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 255,
      physicalDef: 0,
    },
    imageUrl: host + "126.jpg",
    enhancementsNum: 2,
    equipCost: 64,
    specialEffects: [
      {
        rawText: "ブロック率が40%上昇する",
      },
    ],
  },
  {
    id: 55,
    name: "旧式端末",
    rawName: "旧式端末",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 135,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 100,
    },
    imageUrl: host + "127.jpg",
    enhancementsNum: 0,
    equipCost: 30,
    specialEffects: [],
  },
  {
    id: 56,
    name: "パニッシュメント",
    rawName: "パニッシュメント",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 50,
      physicalDef: 0,
    },
    imageUrl: host + "130.jpg",
    enhancementsNum: 0,
    equipCost: 14,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージ5%増加",
      },
    ],
  },
  {
    id: 57,
    name: "パニッシュメント",
    rawName: "パニッシュメント+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 85,
      physicalDef: 0,
    },
    imageUrl: host + "131.jpg",
    enhancementsNum: 1,
    equipCost: 23,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージ10%増加",
      },
    ],
  },
  {
    id: 58,
    name: "パニッシュメント",
    rawName: "パニッシュメント++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 120,
      physicalDef: 0,
    },
    imageUrl: host + "132.jpg",
    enhancementsNum: 2,
    equipCost: 32,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージ15%増加",
      },
    ],
  },
  {
    id: 59,
    name: "エクセキューション",
    rawName: "エクセキューション",
    attribute: "darkness",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 80,
      physicalDef: 0,
    },
    imageUrl: host + "133.jpg",
    enhancementsNum: 0,
    equipCost: 17,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージ10%増加",
      },
    ],
  },
  {
    id: 60,
    name: "エクセキューション",
    rawName: "エクセキューション+",
    attribute: "darkness",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 135,
      physicalDef: 0,
    },
    imageUrl: host + "134.jpg",
    enhancementsNum: 1,
    equipCost: 27,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージ15%増加",
      },
    ],
  },
  {
    id: 61,
    name: "エクセキューション",
    rawName: "エクセキューション++",
    attribute: "darkness",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 190,
      physicalDef: 0,
    },
    imageUrl: host + "135.jpg",
    enhancementsNum: 2,
    equipCost: 37,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージ20%増加",
      },
    ],
  },
  {
    id: 62,
    name: "センターマイク",
    rawName: "センターマイク",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 54,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "136.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 63,
    name: "センターマイク",
    rawName: "センターマイク+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 108,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "137.jpg",
    enhancementsNum: 1,
    equipCost: 15,
    specialEffects: [],
  },
  {
    id: 64,
    name: "センターマイク",
    rawName: "センターマイク++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 162,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "138.jpg",
    enhancementsNum: 2,
    equipCost: 20,
    specialEffects: [],
  },
  {
    id: 65,
    name: "村雨",
    rawName: "村雨",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 130,
      physicalDef: 0,
    },
    imageUrl: host + "139.jpg",
    enhancementsNum: 0,
    equipCost: 22,
    specialEffects: [],
  },
  {
    id: 66,
    name: "村雨",
    rawName: "村雨+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 200,
      physicalDef: 0,
    },
    imageUrl: host + "140.jpg",
    enhancementsNum: 1,
    equipCost: 32,
    specialEffects: [],
  },
  {
    id: 67,
    name: "村雨",
    rawName: "村雨++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 270,
      physicalDef: 0,
    },
    imageUrl: host + "141.jpg",
    enhancementsNum: 2,
    equipCost: 40,
    specialEffects: [],
  },
  {
    id: 68,
    name: "流水の双剣",
    rawName: "流水の双剣",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 100,
      physicalAtk: 135,
      physicalDef: 0,
    },
    imageUrl: host + "142.jpg",
    enhancementsNum: 0,
    equipCost: 30,
    specialEffects: [],
  },
  {
    id: 69,
    name: "ブロンズソウル",
    rawName: "ブロンズソウル",
    attribute: "darkness",
    statuses: {
      hp: 62,
      magicAtk: 12,
      magicDef: 0,
      physicalAtk: 49,
      physicalDef: 0,
    },
    imageUrl: host + "145.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ5%軽減",
      },
    ],
  },
  {
    id: 70,
    name: "ブロンズソウル",
    rawName: "ブロンズソウル+",
    attribute: "darkness",
    statuses: {
      hp: 135,
      magicAtk: 24,
      magicDef: 0,
      physicalAtk: 98,
      physicalDef: 0,
    },
    imageUrl: host + "146.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ7%軽減",
      },
    ],
  },
  {
    id: 71,
    name: "ブロンズソウル",
    rawName: "ブロンズソウル++",
    attribute: "darkness",
    statuses: {
      hp: 198,
      magicAtk: 36,
      magicDef: 0,
      physicalAtk: 147,
      physicalDef: 0,
    },
    imageUrl: host + "147.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ10%軽減",
      },
    ],
  },
  {
    id: 72,
    name: "アイアンハート",
    rawName: "アイアンハート",
    attribute: "void",
    statuses: {
      hp: 48,
      magicAtk: 10,
      magicDef: 0,
      physicalAtk: 40,
      physicalDef: 0,
    },
    imageUrl: host + "148.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ5%軽減",
      },
    ],
  },
  {
    id: 73,
    name: "アイアンハート",
    rawName: "アイアンハート+",
    attribute: "void",
    statuses: {
      hp: 112,
      magicAtk: 20,
      magicDef: 0,
      physicalAtk: 82,
      physicalDef: 0,
    },
    imageUrl: host + "149.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ7%軽減",
      },
    ],
  },
  {
    id: 74,
    name: "アイアンハート",
    rawName: "アイアンハート++",
    attribute: "void",
    statuses: {
      hp: 160,
      magicAtk: 30,
      magicDef: 0,
      physicalAtk: 124,
      physicalDef: 0,
    },
    imageUrl: host + "150.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "受ける魔法ダメージ10%軽減",
      },
    ],
  },
  {
    id: 75,
    name: "聖樹の木剣",
    rawName: "聖樹の木剣",
    attribute: "void",
    statuses: {
      hp: 70,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 30,
      physicalDef: 0,
    },
    imageUrl: host + "151.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+30%",
      },
    ],
  },
  {
    id: 76,
    name: "聖樹の木剣",
    rawName: "聖樹の木剣+",
    attribute: "void",
    statuses: {
      hp: 135,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 62,
      physicalDef: 0,
    },
    imageUrl: host + "152.jpg",
    enhancementsNum: 1,
    equipCost: 19,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+45%",
      },
    ],
  },
  {
    id: 77,
    name: "聖樹の木剣",
    rawName: "聖樹の木剣++",
    attribute: "void",
    statuses: {
      hp: 200,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 94,
      physicalDef: 0,
    },
    imageUrl: host + "153.jpg",
    enhancementsNum: 2,
    equipCost: 28,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+60%",
      },
    ],
  },
  {
    id: 78,
    name: "クマホ明神",
    rawName: "クマホ明神",
    attribute: "void",
    statuses: {
      hp: 70,
      magicAtk: 30,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "154.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [
      {
        rawText: "行動不能無効化+30%",
      },
    ],
  },
  {
    id: 79,
    name: "クマホ明神",
    rawName: "クマホ明神+",
    attribute: "void",
    statuses: {
      hp: 135,
      magicAtk: 62,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "155.jpg",
    enhancementsNum: 1,
    equipCost: 19,
    specialEffects: [
      {
        rawText: "行動不能無効化+45%",
      },
    ],
  },
  {
    id: 80,
    name: "クマホ明神",
    rawName: "クマホ明神++",
    attribute: "void",
    statuses: {
      hp: 200,
      magicAtk: 94,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "156.jpg",
    enhancementsNum: 2,
    equipCost: 28,
    specialEffects: [
      {
        rawText: "行動不能無効化+60%",
      },
    ],
  },
  {
    id: 81,
    name: "神依木の木剣",
    rawName: "神依木の木剣",
    attribute: "darkness",
    statuses: {
      hp: 110,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 55,
      physicalDef: 0,
    },
    imageUrl: host + "157.jpg",
    enhancementsNum: 0,
    equipCost: 15,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+50%",
      },
    ],
  },
  {
    id: 82,
    name: "神依木の木剣",
    rawName: "神依木の木剣+",
    attribute: "darkness",
    statuses: {
      hp: 190,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 97,
      physicalDef: 0,
    },
    imageUrl: host + "158.jpg",
    enhancementsNum: 1,
    equipCost: 24,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+75%",
      },
    ],
  },
  {
    id: 83,
    name: "神依木の木剣",
    rawName: "神依木の木剣++",
    attribute: "darkness",
    statuses: {
      hp: 270,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 140,
      physicalDef: 0,
    },
    imageUrl: host + "159.jpg",
    enhancementsNum: 2,
    equipCost: 33,
    specialEffects: [
      {
        rawText: "幻惑無効化確率+100%",
      },
    ],
  },
  {
    id: 84,
    name: "クマホ大明神",
    rawName: "クマホ大明神",
    attribute: "wind",
    statuses: {
      hp: 110,
      magicAtk: 55,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "160.jpg",
    enhancementsNum: 0,
    equipCost: 15,
    specialEffects: [
      {
        rawText: "行動不能無効化+50%",
      },
    ],
  },
  {
    id: 85,
    name: "クマホ大明神",
    rawName: "クマホ大明神+",
    attribute: "wind",
    statuses: {
      hp: 190,
      magicAtk: 97,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "161.jpg",
    enhancementsNum: 1,
    equipCost: 24,
    specialEffects: [
      {
        rawText: "行動不能無効化+75%",
      },
    ],
  },
  {
    id: 86,
    name: "クマホ大明神",
    rawName: "クマホ大明神++",
    attribute: "wind",
    statuses: {
      hp: 270,
      magicAtk: 140,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "162.jpg",
    enhancementsNum: 2,
    equipCost: 33,
    specialEffects: [
      {
        rawText: "行動不能無効化+100%",
      },
    ],
  },
  {
    id: 87,
    name: "双翼の氷晶",
    rawName: "双翼の氷晶",
    attribute: "void",
    statuses: {
      hp: 210,
      magicAtk: 82,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "163.jpg",
    enhancementsNum: 0,
    equipCost: 23,
    specialEffects: [
      {
        rawText: "クリティカル率+15%",
      },
    ],
  },
  {
    id: 88,
    name: "双翼の氷晶",
    rawName: "双翼の氷晶+",
    attribute: "void",
    statuses: {
      hp: 410,
      magicAtk: 152,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "164.jpg",
    enhancementsNum: 1,
    equipCost: 43,
    specialEffects: [
      {
        rawText: "クリティカル率+25%",
      },
    ],
  },
  {
    id: 89,
    name: "双翼の氷晶",
    rawName: "双翼の氷晶++",
    attribute: "void",
    statuses: {
      hp: 610,
      magicAtk: 222,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "165.jpg",
    enhancementsNum: 2,
    equipCost: 63,
    specialEffects: [
      {
        rawText: "クリティカル率+35%",
      },
    ],
  },
  {
    id: 90,
    name: "金獣の大槌",
    rawName: "金獣の大槌",
    attribute: "void",
    statuses: {
      hp: 190,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 76,
      physicalDef: 0,
    },
    imageUrl: host + "166.jpg",
    enhancementsNum: 0,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "クリティカル率+15%",
      },
    ],
  },
  {
    id: 91,
    name: "金獣の大槌",
    rawName: "金獣の大槌+",
    attribute: "void",
    statuses: {
      hp: 390,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 146,
      physicalDef: 0,
    },
    imageUrl: host + "167.jpg",
    enhancementsNum: 1,
    equipCost: 41,
    specialEffects: [
      {
        rawText: "クリティカル率+25%",
      },
    ],
  },
  {
    id: 92,
    name: "金獣の大槌",
    rawName: "金獣の大槌++",
    attribute: "void",
    statuses: {
      hp: 590,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 216,
      physicalDef: 0,
    },
    imageUrl: host + "168.jpg",
    enhancementsNum: 2,
    equipCost: 61,
    specialEffects: [
      {
        rawText: "クリティカル率+35%",
      },
    ],
  },
  {
    id: 93,
    name: "ブラックボックス",
    rawName: "ブラックボックス",
    attribute: "fire",
    statuses: {
      hp: 180,
      magicAtk: 66,
      magicDef: 0,
      physicalAtk: 66,
      physicalDef: 0,
    },
    imageUrl: host + "169.jpg",
    enhancementsNum: 0,
    equipCost: 18,
    specialEffects: [
      {
        rawText: "物理・魔法攻撃ダメージ10%増加",
      },
    ],
  },
  {
    id: 94,
    name: "ブラックボックス",
    rawName: "ブラックボックス+",
    attribute: "fire",
    statuses: {
      hp: 355,
      magicAtk: 130,
      magicDef: 0,
      physicalAtk: 130,
      physicalDef: 0,
    },
    imageUrl: host + "170.jpg",
    enhancementsNum: 1,
    equipCost: 35,
    specialEffects: [
      {
        rawText: "物理・魔法攻撃ダメージ18%増加",
      },
    ],
  },
  {
    id: 95,
    name: "ブラックボックス",
    rawName: "ブラックボックス++",
    attribute: "fire",
    statuses: {
      hp: 530,
      magicAtk: 194,
      magicDef: 0,
      physicalAtk: 194,
      physicalDef: 0,
    },
    imageUrl: host + "171.jpg",
    enhancementsNum: 2,
    equipCost: 52,
    specialEffects: [
      {
        rawText: "物理・魔法攻撃ダメージ25%増加",
      },
    ],
  },
  {
    id: 96,
    name: "パルス・ブラスター",
    rawName: "パルス・ブラスター",
    attribute: "wind",
    statuses: {
      hp: 160,
      magicAtk: 59,
      magicDef: 0,
      physicalAtk: 59,
      physicalDef: 0,
    },
    imageUrl: host + "172.jpg",
    enhancementsNum: 0,
    equipCost: 16,
    specialEffects: [
      {
        rawText: "物理・魔法攻撃ダメージ10%増加",
      },
    ],
  },
  {
    id: 97,
    name: "パルス・ブラスター",
    rawName: "パルス・ブラスター+",
    attribute: "wind",
    statuses: {
      hp: 335,
      magicAtk: 122,
      magicDef: 0,
      physicalAtk: 122,
      physicalDef: 0,
    },
    imageUrl: host + "173.jpg",
    enhancementsNum: 1,
    equipCost: 33,
    specialEffects: [
      {
        rawText: "物理・魔法攻撃ダメージ18%増加",
      },
    ],
  },
  {
    id: 98,
    name: "パルス・ブラスター",
    rawName: "パルス・ブラスター++",
    attribute: "wind",
    statuses: {
      hp: 510,
      magicAtk: 185,
      magicDef: 0,
      physicalAtk: 185,
      physicalDef: 0,
    },
    imageUrl: host + "174.jpg",
    enhancementsNum: 2,
    equipCost: 50,
    specialEffects: [
      {
        rawText: "物理・魔法攻撃ダメージ25%増加",
      },
    ],
  },
  {
    id: 99,
    name: "イビルアイ・ランス",
    rawName: "イビルアイ・ランス",
    attribute: "darkness",
    statuses: {
      hp: 190,
      magicAtk: 70,
      magicDef: 0,
      physicalAtk: 70,
      physicalDef: 0,
    },
    imageUrl: host + "175.jpg",
    enhancementsNum: 0,
    equipCost: 19,
    specialEffects: [
      {
        rawText: "クリティカル率+10%",
      },
    ],
  },
  {
    id: 100,
    name: "イビルアイ・ランス",
    rawName: "イビルアイ・ランス+",
    attribute: "darkness",
    statuses: {
      hp: 365,
      magicAtk: 134,
      magicDef: 0,
      physicalAtk: 134,
      physicalDef: 0,
    },
    imageUrl: host + "176.jpg",
    enhancementsNum: 1,
    equipCost: 36,
    specialEffects: [
      {
        rawText: "クリティカル率+20%",
      },
    ],
  },
  {
    id: 101,
    name: "イビルアイ・ランス",
    rawName: "イビルアイ・ランス++",
    attribute: "darkness",
    statuses: {
      hp: 540,
      magicAtk: 198,
      magicDef: 0,
      physicalAtk: 198,
      physicalDef: 0,
    },
    imageUrl: host + "177.jpg",
    enhancementsNum: 2,
    equipCost: 53,
    specialEffects: [
      {
        rawText: "クリティカル率+30%",
      },
    ],
  },
  {
    id: 102,
    name: "フェアリーグレイス",
    rawName: "フェアリーグレイス",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 130,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "178.jpg",
    enhancementsNum: 0,
    equipCost: 22,
    specialEffects: [],
  },
  {
    id: 103,
    name: "フェアリーグレイス",
    rawName: "フェアリーグレイス+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 200,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "179.jpg",
    enhancementsNum: 1,
    equipCost: 32,
    specialEffects: [],
  },
  {
    id: 104,
    name: "フェアリーグレイス",
    rawName: "フェアリーグレイス++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 270,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "180.jpg",
    enhancementsNum: 2,
    equipCost: 40,
    specialEffects: [],
  },
  {
    id: 105,
    name: "鞘より抜かれし剣",
    rawName: "鞘より抜かれし剣",
    attribute: "void",
    statuses: {
      hp: 81,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 34,
      physicalDef: 0,
    },
    imageUrl: host + "181.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "睡眠を30%の確率で無効化する",
      },
    ],
  },
  {
    id: 106,
    name: "鞘より抜かれし剣",
    rawName: "鞘より抜かれし剣+",
    attribute: "void",
    statuses: {
      hp: 157,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 72,
      physicalDef: 0,
    },
    imageUrl: host + "182.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "睡眠を45%の確率で無効化する",
      },
    ],
  },
  {
    id: 107,
    name: "鞘より抜かれし剣",
    rawName: "鞘より抜かれし剣++",
    attribute: "void",
    statuses: {
      hp: 233,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 110,
      physicalDef: 0,
    },
    imageUrl: host + "183.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "睡眠を60%の確率で無効化する",
      },
    ],
  },
  {
    id: 108,
    name: "テオス・クシフォス",
    rawName: "テオス・クシフォス",
    attribute: "light",
    statuses: {
      hp: 102,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 40,
      physicalDef: 0,
    },
    imageUrl: host + "184.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "睡眠を40%の確率で無効化する",
      },
    ],
  },
  {
    id: 109,
    name: "テオス・クシフォス",
    rawName: "テオス・クシフォス+",
    attribute: "light",
    statuses: {
      hp: 191,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 88,
      physicalDef: 0,
    },
    imageUrl: host + "185.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "睡眠を60%の確率で無効化する",
      },
    ],
  },
  {
    id: 110,
    name: "クルーエルワンド",
    rawName: "クルーエルワンド",
    attribute: "water",
    statuses: {
      hp: 170,
      magicAtk: 63,
      magicDef: 0,
      physicalAtk: 63,
      physicalDef: 0,
    },
    imageUrl: host + "187.jpg",
    enhancementsNum: 0,
    equipCost: 17,
    specialEffects: [
      {
        rawText: "物理・魔法攻撃ダメージ10%増加",
      },
    ],
  },
  {
    id: 111,
    name: "クルーエルワンド",
    rawName: "クルーエルワンド+",
    attribute: "water",
    statuses: {
      hp: 345,
      magicAtk: 126,
      magicDef: 0,
      physicalAtk: 126,
      physicalDef: 0,
    },
    imageUrl: host + "188.jpg",
    enhancementsNum: 1,
    equipCost: 34,
    specialEffects: [
      {
        rawText: "物理・魔法攻撃ダメージ18%増加",
      },
    ],
  },
  {
    id: 112,
    name: "クルーエルワンド",
    rawName: "クルーエルワンド++",
    attribute: "water",
    statuses: {
      hp: 520,
      magicAtk: 190,
      magicDef: 0,
      physicalAtk: 190,
      physicalDef: 0,
    },
    imageUrl: host + "189.jpg",
    enhancementsNum: 2,
    equipCost: 51,
    specialEffects: [
      {
        rawText: "物理・魔法攻撃ダメージ25%増加",
      },
    ],
  },
  {
    id: 113,
    name: "プルガトリオ",
    rawName: "プルガトリオ",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 40,
      magicDef: 0,
      physicalAtk: 40,
      physicalDef: 0,
    },
    imageUrl: host + "193.jpg",
    enhancementsNum: 0,
    equipCost: 7,
    specialEffects: [],
  },
  {
    id: 114,
    name: "プルガトリオ",
    rawName: "プルガトリオ+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 80,
      magicDef: 0,
      physicalAtk: 80,
      physicalDef: 0,
    },
    imageUrl: host + "194.jpg",
    enhancementsNum: 1,
    equipCost: 11,
    specialEffects: [],
  },
  {
    id: 115,
    name: "旧式写真機",
    rawName: "旧式写真機",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 120,
      magicDef: 75,
      physicalAtk: 120,
      physicalDef: 75,
    },
    imageUrl: host + "196.jpg",
    enhancementsNum: 0,
    equipCost: 30,
    specialEffects: [],
  },
  {
    id: 116,
    name: "旧式写真機",
    rawName: "旧式写真機+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 180,
      magicDef: 113,
      physicalAtk: 180,
      physicalDef: 113,
    },
    imageUrl: host + "197.jpg",
    enhancementsNum: 1,
    equipCost: 45,
    specialEffects: [],
  },
  {
    id: 117,
    name: "肉まんおばけ",
    rawName: "肉まんおばけ",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 36,
      magicDef: 0,
      physicalAtk: 36,
      physicalDef: 0,
    },
    imageUrl: host + "202.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "会心率+8%",
      },
    ],
  },
  {
    id: 118,
    name: "肉まんおばけ",
    rawName: "肉まんおばけ+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 80,
      magicDef: 0,
      physicalAtk: 80,
      physicalDef: 0,
    },
    imageUrl: host + "203.jpg",
    enhancementsNum: 1,
    equipCost: 23,
    specialEffects: [
      {
        rawText: "会心率+14%",
      },
    ],
  },
  {
    id: 119,
    name: "肉まんおばけ",
    rawName: "肉まんおばけ++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 124,
      magicDef: 0,
      physicalAtk: 124,
      physicalDef: 0,
    },
    imageUrl: host + "204.jpg",
    enhancementsNum: 2,
    equipCost: 34,
    specialEffects: [
      {
        rawText: "会心率+20%",
      },
    ],
  },
  {
    id: 120,
    name: "上杉家のカレー",
    rawName: "上杉家のカレー",
    attribute: "fire",
    statuses: {
      hp: 0,
      magicAtk: 50,
      magicDef: 0,
      physicalAtk: 50,
      physicalDef: 0,
    },
    imageUrl: host + "205.jpg",
    enhancementsNum: 0,
    equipCost: 14,
    specialEffects: [
      {
        rawText: "会心率+11%",
      },
    ],
  },
  {
    id: 121,
    name: "上杉家のカレー",
    rawName: "上杉家のカレー+",
    attribute: "fire",
    statuses: {
      hp: 0,
      magicAtk: 107,
      magicDef: 0,
      physicalAtk: 107,
      physicalDef: 0,
    },
    imageUrl: host + "206.jpg",
    enhancementsNum: 1,
    equipCost: 26,
    specialEffects: [
      {
        rawText: "会心率+18%",
      },
    ],
  },
  {
    id: 122,
    name: "上杉家のカレー",
    rawName: "上杉家のカレー++",
    attribute: "fire",
    statuses: {
      hp: 0,
      magicAtk: 164,
      magicDef: 0,
      physicalAtk: 164,
      physicalDef: 0,
    },
    imageUrl: host + "207.jpg",
    enhancementsNum: 2,
    equipCost: 38,
    specialEffects: [
      {
        rawText: "会心率+25%",
      },
    ],
  },
  {
    id: 123,
    name: "混沌の旋刃",
    rawName: "混沌の旋刃",
    attribute: "void",
    statuses: {
      hp: 180,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 72,
      physicalDef: 0,
    },
    imageUrl: host + "208.jpg",
    enhancementsNum: 0,
    equipCost: 20,
    specialEffects: [
      {
        rawText: "物理ダメージ10%増加",
      },
    ],
  },
  {
    id: 124,
    name: "混沌の旋刃",
    rawName: "混沌の旋刃+",
    attribute: "void",
    statuses: {
      hp: 380,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 142,
      physicalDef: 0,
    },
    imageUrl: host + "209.jpg",
    enhancementsNum: 1,
    equipCost: 40,
    specialEffects: [
      {
        rawText: "物理ダメージ20%増加",
      },
    ],
  },
  {
    id: 125,
    name: "混沌の旋刃",
    rawName: "混沌の旋刃++",
    attribute: "void",
    statuses: {
      hp: 580,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 212,
      physicalDef: 0,
    },
    imageUrl: host + "210.jpg",
    enhancementsNum: 2,
    equipCost: 60,
    specialEffects: [
      {
        rawText: "物理ダメージ30%増加",
      },
    ],
  },
  {
    id: 126,
    name: "混沌の円環",
    rawName: "混沌の円環",
    attribute: "void",
    statuses: {
      hp: 230,
      magicAtk: 88,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "211.jpg",
    enhancementsNum: 0,
    equipCost: 25,
    specialEffects: [
      {
        rawText: "ブロック率15%上昇",
      },
    ],
  },
  {
    id: 127,
    name: "混沌の円環",
    rawName: "混沌の円環+",
    attribute: "void",
    statuses: {
      hp: 430,
      magicAtk: 158,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "212.jpg",
    enhancementsNum: 1,
    equipCost: 45,
    specialEffects: [
      {
        rawText: "ブロック率27%上昇",
      },
    ],
  },
  {
    id: 128,
    name: "混沌の円環",
    rawName: "混沌の円環++",
    attribute: "void",
    statuses: {
      hp: 630,
      magicAtk: 228,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "213.jpg",
    enhancementsNum: 2,
    equipCost: 65,
    specialEffects: [
      {
        rawText: "ブロック率40%上昇",
      },
    ],
  },
  {
    id: 129,
    name: "イビルチェスト",
    rawName: "イビルチェスト",
    attribute: "void",
    statuses: {
      hp: 51,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 44,
      physicalDef: 0,
    },
    imageUrl: host + "214.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "毒無効化+30%",
      },
    ],
  },
  {
    id: 130,
    name: "イビルチェスト",
    rawName: "イビルチェスト+",
    attribute: "void",
    statuses: {
      hp: 109,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 87,
      physicalDef: 0,
    },
    imageUrl: host + "215.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "毒無効化+45%",
      },
    ],
  },
  {
    id: 131,
    name: "イビルチェスト",
    rawName: "イビルチェスト++",
    attribute: "void",
    statuses: {
      hp: 167,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 130,
      physicalDef: 0,
    },
    imageUrl: host + "216.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "毒無効化+60%",
      },
    ],
  },
  {
    id: 132,
    name: "デモンズチェスト",
    rawName: "デモンズチェスト",
    attribute: "wind",
    statuses: {
      hp: 65,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 53,
      physicalDef: 0,
    },
    imageUrl: host + "217.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "毒無効化+40%",
      },
    ],
  },
  {
    id: 133,
    name: "デモンズチェスト",
    rawName: "デモンズチェスト+",
    attribute: "wind",
    statuses: {
      hp: 136,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 103,
      physicalDef: 0,
    },
    imageUrl: host + "218.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "毒無効化+60%",
      },
    ],
  },
  {
    id: 134,
    name: "プリニー連射",
    rawName: "プリニー連射",
    attribute: "void",
    statuses: {
      hp: 70,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 36,
      physicalDef: 0,
    },
    imageUrl: host + "222.jpg",
    enhancementsNum: 0,
    equipCost: 11,
    specialEffects: [
      {
        rawText: "物理ダメージ低下を20%の確率で無効化",
      },
    ],
  },
  {
    id: 135,
    name: "プリニー連射",
    rawName: "プリニー連射+",
    attribute: "void",
    statuses: {
      hp: 135,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 79,
      physicalDef: 0,
    },
    imageUrl: host + "223.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "物理ダメージ低下を35%の確率で無効化",
      },
    ],
  },
  {
    id: 136,
    name: "プリニー連射",
    rawName: "プリニー連射++",
    attribute: "void",
    statuses: {
      hp: 200,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 122,
      physicalDef: 0,
    },
    imageUrl: host + "224.jpg",
    enhancementsNum: 2,
    equipCost: 31,
    specialEffects: [
      {
        rawText: "物理ダメージ低下を50%の確率で無効化",
      },
    ],
  },
  {
    id: 137,
    name: "プリニーボマー",
    rawName: "プリニーボマー",
    attribute: "fire",
    statuses: {
      hp: 90,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 50,
      physicalDef: 0,
    },
    imageUrl: host + "225.jpg",
    enhancementsNum: 0,
    equipCost: 13,
    specialEffects: [
      {
        rawText: "物理ダメージ低下を30%の確率で無効化",
      },
    ],
  },
  {
    id: 138,
    name: "プリニーボマー",
    rawName: "プリニーボマー+",
    attribute: "fire",
    statuses: {
      hp: 180,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 108,
      physicalDef: 0,
    },
    imageUrl: host + "226.jpg",
    enhancementsNum: 1,
    equipCost: 24,
    specialEffects: [
      {
        rawText: "物理ダメージ低下を50%の確率で無効化",
      },
    ],
  },
  {
    id: 139,
    name: "プリニーボマー",
    rawName: "プリニーボマー++",
    attribute: "fire",
    statuses: {
      hp: 270,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 166,
      physicalDef: 0,
    },
    imageUrl: host + "227.jpg",
    enhancementsNum: 2,
    equipCost: 35,
    specialEffects: [
      {
        rawText: "物理ダメージ低下を70%の確率で無効化",
      },
    ],
  },
  {
    id: 140,
    name: "忘竜の献花",
    rawName: "忘竜の献花",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 73,
      magicDef: 0,
      physicalAtk: 73,
      physicalDef: 0,
    },
    imageUrl: host + "231.jpg",
    enhancementsNum: 0,
    equipCost: 13,
    specialEffects: [],
  },
  {
    id: 141,
    name: "忘竜の献花",
    rawName: "忘竜の献花+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 158,
      magicDef: 0,
      physicalAtk: 158,
      physicalDef: 0,
    },
    imageUrl: host + "232.jpg",
    enhancementsNum: 1,
    equipCost: 23,
    specialEffects: [],
  },
  {
    id: 142,
    name: "忘竜の献花",
    rawName: "忘竜の献花++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 243,
      magicDef: 0,
      physicalAtk: 243,
      physicalDef: 0,
    },
    imageUrl: host + "233.jpg",
    enhancementsNum: 2,
    equipCost: 33,
    specialEffects: [],
  },
  {
    id: 143,
    name: "傲慢のアラーニェ",
    rawName: "傲慢のアラーニェ",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 140,
      magicDef: 0,
      physicalAtk: 140,
      physicalDef: 0,
    },
    imageUrl: host + "234.jpg",
    enhancementsNum: 0,
    equipCost: 25,
    specialEffects: [],
  },
  {
    id: 144,
    name: "傲慢のアラーニェ",
    rawName: "傲慢のアラーニェ+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 233,
      magicDef: 0,
      physicalAtk: 233,
      physicalDef: 0,
    },
    imageUrl: host + "235.jpg",
    enhancementsNum: 1,
    equipCost: 38,
    specialEffects: [],
  },
  {
    id: 145,
    name: "傲慢のアラーニェ",
    rawName: "傲慢のアラーニェ++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 326,
      magicDef: 0,
      physicalAtk: 326,
      physicalDef: 0,
    },
    imageUrl: host + "236.jpg",
    enhancementsNum: 2,
    equipCost: 51,
    specialEffects: [],
  },
  {
    id: 146,
    name: "大千鳥十文字槍・朱",
    rawName: "大千鳥十文字槍・朱",
    attribute: "fire",
    statuses: {
      hp: 97,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 41,
      physicalDef: 0,
    },
    imageUrl: host + "237.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "物理ダメ増加",
      },
    ],
  },
  {
    id: 147,
    name: "大千鳥十文字槍・朱",
    rawName: "大千鳥十文字槍・朱+",
    attribute: "fire",
    statuses: {
      hp: 184,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 90,
      physicalDef: 0,
    },
    imageUrl: host + "238.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "物理ダメ増加",
      },
    ],
  },
  {
    id: 148,
    name: "大千鳥十文字槍・朱",
    rawName: "大千鳥十文字槍・朱++",
    attribute: "fire",
    statuses: {
      hp: 271,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 139,
      physicalDef: 0,
    },
    imageUrl: host + "239.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "物理ダメ増加",
      },
    ],
  },
  {
    id: 149,
    name: "大千鳥十文字槍・鐵",
    rawName: "大千鳥十文字槍・鐵",
    attribute: "void",
    statuses: {
      hp: 78,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 34,
      physicalDef: 0,
    },
    imageUrl: host + "240.jpg",
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "物理ダメ増加",
      },
    ],
  },
  {
    id: 150,
    name: "大千鳥十文字槍・鐵",
    rawName: "大千鳥十文字槍・鐵+",
    attribute: "void",
    statuses: {
      hp: 152,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 73,
      physicalDef: 0,
    },
    imageUrl: host + "241.jpg",
    enhancementsNum: 1,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "物理ダメ増加",
      },
    ],
  },
  {
    id: 151,
    name: "大千鳥十文字槍・鐵",
    rawName: "大千鳥十文字槍・鐵++",
    attribute: "void",
    statuses: {
      hp: 226,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 112,
      physicalDef: 0,
    },
    imageUrl: host + "242.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "物理ダメ増加",
      },
    ],
  },
  {
    id: 152,
    name: "スタービーチボール",
    rawName: "スタービーチボール",
    attribute: "void",
    statuses: {
      hp: 50,
      magicAtk: 35,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "243.jpg",
    enhancementsNum: 0,
    equipCost: 11,
    specialEffects: [
      {
        rawText: "物理ダメージ5%軽減",
      },
    ],
  },
  {
    id: 153,
    name: "スタービーチボール",
    rawName: "スタービーチボール+",
    attribute: "void",
    statuses: {
      hp: 112,
      magicAtk: 73,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "244.jpg",
    enhancementsNum: 1,
    equipCost: 19,
    specialEffects: [
      {
        rawText: "物理ダメージ7%軽減",
      },
    ],
  },
  {
    id: 154,
    name: "スタービーチボール",
    rawName: "スタービーチボール++",
    attribute: "void",
    statuses: {
      hp: 174,
      magicAtk: 111,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "245.jpg",
    enhancementsNum: 2,
    equipCost: 27,
    specialEffects: [
      {
        rawText: "物理ダメージ10%軽減",
      },
    ],
  },
  {
    id: 155,
    name: "一千貫き",
    rawName: "一千貫き",
    attribute: "void",
    statuses: {
      hp: 50,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 35,
      physicalDef: 0,
    },
    imageUrl: host + "246.jpg",
    enhancementsNum: 0,
    equipCost: 11,
    specialEffects: [
      {
        rawText: "魔法ダメージ5%軽減",
      },
    ],
  },
  {
    id: 156,
    name: "一千貫き",
    rawName: "一千貫き+",
    attribute: "void",
    statuses: {
      hp: 112,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 73,
      physicalDef: 0,
    },
    imageUrl: host + "247.jpg",
    enhancementsNum: 1,
    equipCost: 19,
    specialEffects: [
      {
        rawText: "魔法ダメージ7%軽減",
      },
    ],
  },
  {
    id: 157,
    name: "一千貫き",
    rawName: "一千貫き++",
    attribute: "void",
    statuses: {
      hp: 174,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 111,
      physicalDef: 0,
    },
    imageUrl: host + "248.jpg",
    enhancementsNum: 2,
    equipCost: 27,
    specialEffects: [
      {
        rawText: "魔法ダメージ10%軽減",
      },
    ],
  },
  {
    id: 158,
    name: "宵を貫く星芒",
    rawName: "宵を貫く星芒",
    attribute: "light",
    statuses: {
      hp: 0,
      magicAtk: 33,
      magicDef: 0,
      physicalAtk: 33,
      physicalDef: 0,
    },
    imageUrl: host + "249.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [
      {
        rawText: "物理・魔法ダメージを3%軽減",
      },
    ],
  },
  {
    id: 159,
    name: "宵を貫く星芒",
    rawName: "宵を貫く星芒+",
    attribute: "light",
    statuses: {
      hp: 0,
      magicAtk: 89,
      magicDef: 0,
      physicalAtk: 89,
      physicalDef: 0,
    },
    imageUrl: host + "250.jpg",
    enhancementsNum: 1,
    equipCost: 20,
    specialEffects: [
      {
        rawText: "物理・魔法ダメージを5%軽減",
      },
    ],
  },
  {
    id: 160,
    name: "宵を貫く星芒",
    rawName: "宵を貫く星芒++",
    attribute: "light",
    statuses: {
      hp: 0,
      magicAtk: 145,
      magicDef: 0,
      physicalAtk: 145,
      physicalDef: 0,
    },
    imageUrl: host + "251.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "物理・魔法ダメージを8%軽減",
      },
    ],
  },
  {
    id: 161,
    name: "戯れのアンサンブル",
    rawName: "戯れのアンサンブル",
    attribute: "water",
    statuses: {
      hp: 0,
      magicAtk: 33,
      magicDef: 0,
      physicalAtk: 33,
      physicalDef: 0,
    },
    imageUrl: host + "252.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [
      {
        rawText: "物理・魔法ダメージを3%軽減",
      },
    ],
  },
  {
    id: 162,
    name: "戯れのアンサンブル",
    rawName: "戯れのアンサンブル+",
    attribute: "water",
    statuses: {
      hp: 0,
      magicAtk: 89,
      magicDef: 0,
      physicalAtk: 89,
      physicalDef: 0,
    },
    imageUrl: host + "253.jpg",
    enhancementsNum: 1,
    equipCost: 20,
    specialEffects: [
      {
        rawText: "物理・魔法ダメージを5%軽減",
      },
    ],
  },
  {
    id: 163,
    name: "戯れのアンサンブル",
    rawName: "戯れのアンサンブル++",
    attribute: "water",
    statuses: {
      hp: 0,
      magicAtk: 145,
      magicDef: 0,
      physicalAtk: 145,
      physicalDef: 0,
    },
    imageUrl: host + "254.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "物理・魔法ダメージを8%軽減",
      },
    ],
  },
  {
    id: 164,
    name: "赤誠の情剣",
    rawName: "赤誠の情剣",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 56,
      magicDef: 0,
      physicalAtk: 56,
      physicalDef: 0,
    },
    imageUrl: host + "255.jpg",
    enhancementsNum: 0,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 165,
    name: "赤誠の情剣",
    rawName: "赤誠の情剣+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 120,
      magicDef: 0,
      physicalAtk: 120,
      physicalDef: 0,
    },
    imageUrl: host + "256.jpg",
    enhancementsNum: 1,
    equipCost: 17,
    specialEffects: [],
  },
  {
    id: 166,
    name: "赤誠の情剣",
    rawName: "赤誠の情剣++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 184,
      magicDef: 0,
      physicalAtk: 184,
      physicalDef: 0,
    },
    imageUrl: host + "257.jpg",
    enhancementsNum: 2,
    equipCost: 24,
    specialEffects: [],
  },
  {
    id: 167,
    name: "カリス・メイス",
    rawName: "カリス・メイス",
    attribute: "void",
    statuses: {
      hp: 50,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 35,
      physicalDef: 0,
    },
    imageUrl: host + "258.jpg",
    enhancementsNum: 0,
    equipCost: 11,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージを5%軽減",
      },
    ],
  },
  {
    id: 168,
    name: "カリス・メイス",
    rawName: "カリス・メイス+",
    attribute: "void",
    statuses: {
      hp: 112,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 73,
      physicalDef: 0,
    },
    imageUrl: host + "259.jpg",
    enhancementsNum: 1,
    equipCost: 19,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージを7%軽減",
      },
    ],
  },
  {
    id: 169,
    name: "カリス・メイス",
    rawName: "カリス・メイス++",
    attribute: "void",
    statuses: {
      hp: 174,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 111,
      physicalDef: 0,
    },
    imageUrl: host + "260.jpg",
    enhancementsNum: 2,
    equipCost: 27,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージを10%軽減",
      },
    ],
  },
  {
    id: 170,
    name: "不沈艦エピタフ",
    rawName: "不沈艦エピタフ",
    attribute: "void",
    statuses: {
      hp: 50,
      magicAtk: 35,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "261.jpg",
    enhancementsNum: 0,
    equipCost: 11,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージを5%軽減",
      },
    ],
  },
  {
    id: 171,
    name: "不沈艦エピタフ",
    rawName: "不沈艦エピタフ+",
    attribute: "void",
    statuses: {
      hp: 112,
      magicAtk: 73,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "262.jpg",
    enhancementsNum: 1,
    equipCost: 19,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージを7%軽減",
      },
    ],
  },
  {
    id: 172,
    name: "不沈艦エピタフ",
    rawName: "不沈艦エピタフ++",
    attribute: "void",
    statuses: {
      hp: 174,
      magicAtk: 111,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "263.jpg",
    enhancementsNum: 2,
    equipCost: 27,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージを10%軽減",
      },
    ],
  },
  {
    id: 173,
    name: "デモンズチェスト",
    rawName: "デモンズチェスト++",
    attribute: "wind",
    statuses: {
      hp: 207,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 153,
      physicalDef: 0,
    },
    imageUrl: host + "264.jpg",
    enhancementsNum: 2,
    equipCost: 30,
    specialEffects: [
      {
        rawText: "毒無効化+80%",
      },
    ],
  },
  {
    id: 174,
    name: "ゼロアワーアタック",
    rawName: "ゼロアワーアタック",
    attribute: "void",
    statuses: {
      hp: 500,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 0,
    equipCost: 21,
    specialEffects: [
      {
        rawText: "ブロック率が20%上昇する",
      },
    ],
  },
  {
    id: 175,
    name: "ゼロアワーアタック",
    rawName: "ゼロアワーアタック+",
    attribute: "void",
    statuses: {
      hp: 1000,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 1,
    equipCost: 38,
    specialEffects: [
      {
        rawText: "ブロック率が35%上昇する",
      },
    ],
  },
  {
    id: 176,
    name: "ゼロアワーアタック",
    rawName: "ゼロアワーアタック++",
    attribute: "void",
    statuses: {
      hp: 1500,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 2,
    equipCost: 55,
    specialEffects: [
      {
        rawText: "ブロック率が50%上昇する",
      },
    ],
  },
  {
    id: 177,
    name: "ファイアシェル",
    rawName: "ファイアシェル",
    attribute: "fire",
    statuses: {
      hp: 150,
      magicAtk: 60,
      magicDef: 0,
      physicalAtk: 60,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 0,
    equipCost: 16,
    specialEffects: [
      {
        rawText: "火属性耐性が15%上昇する",
      },
    ],
  },
  {
    id: 178,
    name: "ファイアシェル",
    rawName: "ファイアシェル+",
    attribute: "fire",
    statuses: {
      hp: 325,
      magicAtk: 120,
      magicDef: 0,
      physicalAtk: 120,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 1,
    equipCost: 33,
    specialEffects: [
      {
        rawText: "火属性耐性が30%上昇する",
      },
    ],
  },
  {
    id: 179,
    name: "ファイアシェル",
    rawName: "ファイアシェル++",
    attribute: "fire",
    statuses: {
      hp: 500,
      magicAtk: 180,
      magicDef: 0,
      physicalAtk: 180,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 2,
    equipCost: 50,
    specialEffects: [
      {
        rawText: "火属性耐性が50%上昇する",
      },
    ],
  },
  {
    id: 180,
    name: "ウォーターシェル",
    rawName: "ウォーターシェル",
    attribute: "water",
    statuses: {
      hp: 150,
      magicAtk: 60,
      magicDef: 0,
      physicalAtk: 60,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 0,
    equipCost: 16,
    specialEffects: [
      {
        rawText: "水属性耐性が15%上昇する",
      },
    ],
  },
  {
    id: 181,
    name: "ウォーターシェル",
    rawName: "ウォーターシェル+",
    attribute: "water",
    statuses: {
      hp: 325,
      magicAtk: 120,
      magicDef: 0,
      physicalAtk: 120,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 1,
    equipCost: 33,
    specialEffects: [
      {
        rawText: "水属性耐性が30%上昇する",
      },
    ],
  },
  {
    id: 182,
    name: "ウォーターシェル",
    rawName: "ウォーターシェル++",
    attribute: "water",
    statuses: {
      hp: 500,
      magicAtk: 180,
      magicDef: 0,
      physicalAtk: 180,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 2,
    equipCost: 50,
    specialEffects: [
      {
        rawText: "水属性耐性が50%上昇する",
      },
    ],
  },
  {
    id: 183,
    name: "ウィンドシェル",
    rawName: "ウィンドシェル",
    attribute: "wind",
    statuses: {
      hp: 150,
      magicAtk: 60,
      magicDef: 0,
      physicalAtk: 60,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 0,
    equipCost: 16,
    specialEffects: [
      {
        rawText: "風属性耐性が15%上昇する",
      },
    ],
  },
  {
    id: 184,
    name: "ウィンドシェル",
    rawName: "ウィンドシェル+",
    attribute: "wind",
    statuses: {
      hp: 325,
      magicAtk: 120,
      magicDef: 0,
      physicalAtk: 120,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 1,
    equipCost: 33,
    specialEffects: [
      {
        rawText: "風属性耐性が30%上昇する",
      },
    ],
  },
  {
    id: 185,
    name: "ウィンドシェル",
    rawName: "ウィンドシェル++",
    attribute: "wind",
    statuses: {
      hp: 500,
      magicAtk: 180,
      magicDef: 0,
      physicalAtk: 180,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 2,
    equipCost: 50,
    specialEffects: [
      {
        rawText: "風属性耐性が50%上昇する",
      },
    ],
  },
  {
    id: 186,
    name: "ダークシェル",
    rawName: "ダークシェル",
    attribute: "darkness",
    statuses: {
      hp: 150,
      magicAtk: 60,
      magicDef: 0,
      physicalAtk: 60,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 0,
    equipCost: 16,
    specialEffects: [
      {
        rawText: "闇属性耐性が15%上昇する",
      },
    ],
  },
  {
    id: 187,
    name: "ダークシェル",
    rawName: "ダークシェル+",
    attribute: "darkness",
    statuses: {
      hp: 325,
      magicAtk: 120,
      magicDef: 0,
      physicalAtk: 120,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 1,
    equipCost: 33,
    specialEffects: [
      {
        rawText: "闇属性耐性が30%上昇する",
      },
    ],
  },
  {
    id: 188,
    name: "ダークシェル",
    rawName: "ダークシェル++",
    attribute: "darkness",
    statuses: {
      hp: 500,
      magicAtk: 180,
      magicDef: 0,
      physicalAtk: 180,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 2,
    equipCost: 50,
    specialEffects: [
      {
        rawText: "闇属性耐性が50%上昇する",
      },
    ],
  },
  {
    id: 189,
    name: "ライトシェル",
    rawName: "ライトシェル",
    attribute: "light",
    statuses: {
      hp: 150,
      magicAtk: 60,
      magicDef: 0,
      physicalAtk: 60,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 0,
    equipCost: 16,
    specialEffects: [
      {
        rawText: "光属性耐性が15%上昇する",
      },
    ],
  },
  {
    id: 190,
    name: "ライトシェル",
    rawName: "ライトシェル+",
    attribute: "light",
    statuses: {
      hp: 325,
      magicAtk: 120,
      magicDef: 0,
      physicalAtk: 120,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 1,
    equipCost: 33,
    specialEffects: [
      {
        rawText: "光属性耐性が30%上昇する",
      },
    ],
  },
  {
    id: 191,
    name: "ライトシェル",
    rawName: "ライトシェル++",
    attribute: "light",
    statuses: {
      hp: 500,
      magicAtk: 180,
      magicDef: 0,
      physicalAtk: 180,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 2,
    equipCost: 50,
    specialEffects: [
      {
        rawText: "光属性耐性が50%上昇する",
      },
    ],
  },
  {
    id: 192,
    name: "封印の箱",
    rawName: "封印の箱",
    attribute: "void",
    statuses: {
      hp: 48,
      magicAtk: 45,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: null,
    enhancementsNum: 0,
    equipCost: 12,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージ+5%",
      },
    ],
  },
  {
    id: 193,
    name: "チェーンソー",
    rawName: "チェーンソー",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 7,
      magicDef: 0,
      physicalAtk: 26,
      physicalDef: 0,
    },
    imageUrl: host + "13.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 194,
    name: "電磁ロッド",
    rawName: "電磁ロッド",
    attribute: "void",
    statuses: {
      hp: 33,
      magicAtk: 7,
      magicDef: 0,
      physicalAtk: 20,
      physicalDef: 0,
    },
    imageUrl: host + "14.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 195,
    name: "フォースライフル",
    rawName: "フォースライフル",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 26,
      magicDef: 0,
      physicalAtk: 7,
      physicalDef: 0,
    },
    imageUrl: host + "15.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 196,
    name: "フォースマシンガン",
    rawName: "フォースマシンガン",
    attribute: "void",
    statuses: {
      hp: 33,
      magicAtk: 20,
      magicDef: 0,
      physicalAtk: 7,
      physicalDef: 0,
    },
    imageUrl: host + "16.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 197,
    name: "ミサイル",
    rawName: "ミサイル",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 20,
      magicDef: 0,
      physicalAtk: 20,
      physicalDef: 0,
    },
    imageUrl: host + "17.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 198,
    name: "ロケットランチャー",
    rawName: "ロケットランチャー",
    attribute: "void",
    statuses: {
      hp: 33,
      magicAtk: 17,
      magicDef: 0,
      physicalAtk: 17,
      physicalDef: 0,
    },
    imageUrl: host + "18.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 199,
    name: "チェーンソー",
    rawName: "チェーンソー+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 13,
      magicDef: 0,
      physicalAtk: 51,
      physicalDef: 0,
    },
    imageUrl: host + "31.jpg",
    enhancementsNum: 1,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 200,
    name: "電磁ロッド",
    rawName: "電磁ロッド+",
    attribute: "void",
    statuses: {
      hp: 64,
      magicAtk: 13,
      magicDef: 0,
      physicalAtk: 38,
      physicalDef: 0,
    },
    imageUrl: host + "32.jpg",
    enhancementsNum: 1,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 201,
    name: "フォースライフル",
    rawName: "フォースライフル+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 51,
      magicDef: 0,
      physicalAtk: 13,
      physicalDef: 0,
    },
    imageUrl: host + "33.jpg",
    enhancementsNum: 1,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 202,
    name: "フォースマシンガン",
    rawName: "フォースマシンガン+",
    attribute: "void",
    statuses: {
      hp: 64,
      magicAtk: 38,
      magicDef: 0,
      physicalAtk: 13,
      physicalDef: 0,
    },
    imageUrl: host + "34.jpg",
    enhancementsNum: 1,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 203,
    name: "ミサイル",
    rawName: "ミサイル+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 38,
      magicDef: 0,
      physicalAtk: 38,
      physicalDef: 0,
    },
    imageUrl: host + "35.jpg",
    enhancementsNum: 1,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 204,
    name: "ロケットランチャー",
    rawName: "ロケットランチャー+",
    attribute: "void",
    statuses: {
      hp: 64,
      magicAtk: 32,
      magicDef: 0,
      physicalAtk: 32,
      physicalDef: 0,
    },
    imageUrl: host + "36.jpg",
    enhancementsNum: 1,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 205,
    name: "チェーンソー",
    rawName: "チェーンソー++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 19,
      magicDef: 0,
      physicalAtk: 76,
      physicalDef: 0,
    },
    imageUrl: host + "49.jpg",
    enhancementsNum: 2,
    equipCost: 14,
    specialEffects: [],
  },
  {
    id: 206,
    name: "電磁ロッド",
    rawName: "電磁ロッド++",
    attribute: "void",
    statuses: {
      hp: 95,
      magicAtk: 19,
      magicDef: 0,
      physicalAtk: 57,
      physicalDef: 0,
    },
    imageUrl: host + "50.jpg",
    enhancementsNum: 2,
    equipCost: 14,
    specialEffects: [],
  },
  {
    id: 207,
    name: "フォースライフル",
    rawName: "フォースライフル++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 76,
      magicDef: 0,
      physicalAtk: 19,
      physicalDef: 0,
    },
    imageUrl: host + "51.jpg",
    enhancementsNum: 2,
    equipCost: 14,
    specialEffects: [],
  },
  {
    id: 208,
    name: "フォースマシンガン",
    rawName: "フォースマシンガン++",
    attribute: "void",
    statuses: {
      hp: 95,
      magicAtk: 57,
      magicDef: 0,
      physicalAtk: 19,
      physicalDef: 0,
    },
    imageUrl: host + "52.jpg",
    enhancementsNum: 2,
    equipCost: 14,
    specialEffects: [],
  },
  {
    id: 209,
    name: "ミサイル",
    rawName: "ミサイル++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 57,
      magicDef: 0,
      physicalAtk: 57,
      physicalDef: 0,
    },
    imageUrl: host + "53.jpg",
    enhancementsNum: 2,
    equipCost: 14,
    specialEffects: [],
  },
  {
    id: 210,
    name: "ロケットランチャー",
    rawName: "ロケットランチャー++",
    attribute: "void",
    statuses: {
      hp: 95,
      magicAtk: 48,
      magicDef: 0,
      physicalAtk: 48,
      physicalDef: 0,
    },
    imageUrl: host + "54.jpg",
    enhancementsNum: 2,
    equipCost: 14,
    specialEffects: [],
  },
  {
    id: 211,
    name: "フェール・スタッフ",
    rawName: "フェール・スタッフ",
    attribute: "water",
    statuses: {
      hp: 0,
      magicAtk: 43,
      magicDef: 0,
      physicalAtk: 11,
      physicalDef: 0,
    },
    imageUrl: host + "55.jpg",
    enhancementsNum: 0,
    equipCost: 9,
    specialEffects: [
      {
        rawText: "毒+40%",
      },
    ],
  },
  {
    id: 212,
    name: "バギー・ブラスター",
    rawName: "バギー・ブラスター",
    attribute: "wind",
    statuses: {
      hp: 54,
      magicAtk: 11,
      magicDef: 0,
      physicalAtk: 32,
      physicalDef: 0,
    },
    imageUrl: host + "56.jpg",
    enhancementsNum: 0,
    equipCost: 9,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージ+5%",
      },
    ],
  },
  {
    id: 213,
    name: "パンドラ・ボックス",
    rawName: "パンドラ・ボックス",
    attribute: "fire",
    statuses: {
      hp: 0,
      magicAtk: 49,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "57.jpg",
    enhancementsNum: 0,
    equipCost: 9,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージ+5%",
      },
    ],
  },
  {
    id: 214,
    name: "エラー・ランス",
    rawName: "エラー・ランス",
    attribute: "darkness",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 49,
      physicalDef: 0,
    },
    imageUrl: host + "58.jpg",
    enhancementsNum: 0,
    equipCost: 9,
    specialEffects: [
      {
        rawText: "行動不能無効化+40%",
      },
    ],
  },
  {
    id: 215,
    name: "セキュリティホール",
    rawName: "セキュリティホール",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 27,
      magicDef: 0,
      physicalAtk: 27,
      physicalDef: 0,
    },
    imageUrl: host + "59.jpg",
    enhancementsNum: 0,
    equipCost: 9,
    specialEffects: [
      {
        rawText: "ブロック確率+10%",
      },
    ],
  },
  {
    id: 216,
    name: "フェール・スタッフ",
    rawName: "フェール・スタッフ+",
    attribute: "water",
    statuses: {
      hp: 0,
      magicAtk: 96,
      magicDef: 0,
      physicalAtk: 24,
      physicalDef: 0,
    },
    imageUrl: host + "60.jpg",
    enhancementsNum: 1,
    equipCost: 17,
    specialEffects: [
      {
        rawText: "毒+60%",
      },
    ],
  },
  {
    id: 217,
    name: "バギー・ブラスター",
    rawName: "バギー・ブラスター+",
    attribute: "wind",
    statuses: {
      hp: 120,
      magicAtk: 24,
      magicDef: 0,
      physicalAtk: 72,
      physicalDef: 0,
    },
    imageUrl: host + "61.jpg",
    enhancementsNum: 1,
    equipCost: 17,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージ+10%",
      },
    ],
  },
  {
    id: 218,
    name: "パンドラ・ボックス",
    rawName: "パンドラ・ボックス+",
    attribute: "fire",
    statuses: {
      hp: 0,
      magicAtk: 108,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "62.jpg",
    enhancementsNum: 1,
    equipCost: 17,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージ+10%",
      },
    ],
  },
  {
    id: 219,
    name: "エラー・ランス",
    rawName: "エラー・ランス+",
    attribute: "darkness",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 108,
      physicalDef: 0,
    },
    imageUrl: host + "63.jpg",
    enhancementsNum: 1,
    equipCost: 17,
    specialEffects: [
      {
        rawText: "行動不能無効化+60%",
      },
    ],
  },
  {
    id: 220,
    name: "セキュリティホール",
    rawName: "セキュリティホール+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 60,
      magicDef: 0,
      physicalAtk: 60,
      physicalDef: 0,
    },
    imageUrl: host + "64.jpg",
    enhancementsNum: 1,
    equipCost: 17,
    specialEffects: [
      {
        rawText: "ブロック確率+15%",
      },
    ],
  },
  {
    id: 221,
    name: "フェール・スタッフ",
    rawName: "フェール・スタッフ++",
    attribute: "water",
    statuses: {
      hp: 0,
      magicAtk: 149,
      magicDef: 0,
      physicalAtk: 37,
      physicalDef: 0,
    },
    imageUrl: host + "65.jpg",
    enhancementsNum: 2,
    equipCost: 25,
    specialEffects: [
      {
        rawText: "毒+80%",
      },
    ],
  },
  {
    id: 222,
    name: "バギー・ブラスター",
    rawName: "バギー・ブラスター++",
    attribute: "wind",
    statuses: {
      hp: 186,
      magicAtk: 37,
      magicDef: 0,
      physicalAtk: 112,
      physicalDef: 0,
    },
    imageUrl: host + "66.jpg",
    enhancementsNum: 2,
    equipCost: 25,
    specialEffects: [
      {
        rawText: "物理攻撃ダメージ+15%",
      },
    ],
  },
  {
    id: 223,
    name: "パンドラ・ボックス",
    rawName: "パンドラ・ボックス++",
    attribute: "fire",
    statuses: {
      hp: 0,
      magicAtk: 167,
      magicDef: 0,
      physicalAtk: 0,
      physicalDef: 0,
    },
    imageUrl: host + "67.jpg",
    enhancementsNum: 2,
    equipCost: 25,
    specialEffects: [
      {
        rawText: "魔法攻撃ダメージ+15%",
      },
    ],
  },
  {
    id: 224,
    name: "エラー・ランス",
    rawName: "エラー・ランス++",
    attribute: "darkness",
    statuses: {
      hp: 0,
      magicAtk: 0,
      magicDef: 0,
      physicalAtk: 168,
      physicalDef: 0,
    },
    imageUrl: host + "68.jpg",
    enhancementsNum: 2,
    equipCost: 25,
    specialEffects: [
      {
        rawText: "行動不能無効化+80%",
      },
    ],
  },
  {
    id: 225,
    name: "セキュリティホール",
    rawName: "セキュリティホール++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 93,
      magicDef: 0,
      physicalAtk: 93,
      physicalDef: 0,
    },
    imageUrl: host + "69.jpg",
    enhancementsNum: 2,
    equipCost: 25,
    specialEffects: [
      {
        rawText: "ブロック確率+20%",
      },
    ],
  },
  {
    id: 226,
    name: "テラーファング",
    rawName: "テラーファング",
    attribute: "darkness",
    statuses: {
      hp: 0,
      magicAtk: 47,
      magicDef: 0,
      physicalAtk: 47,
      physicalDef: 0,
    },
    imageUrl: host + "190.jpg",
    enhancementsNum: 0,
    equipCost: 9,
    specialEffects: [
      {
        rawText: "眠り無効化確率+40%",
      },
    ],
  },
  {
    id: 227,
    name: "テラーファング",
    rawName: "テラーファング+",
    attribute: "darkness",
    statuses: {
      hp: 0,
      magicAtk: 108,
      magicDef: 0,
      physicalAtk: 108,
      physicalDef: 0,
    },
    imageUrl: host + "191.jpg",
    enhancementsNum: 1,
    equipCost: 18,
    specialEffects: [
      {
        rawText: "眠り無効化確率+60%",
      },
    ],
  },
  {
    id: 228,
    name: "テラーファング",
    rawName: "テラーファング++",
    attribute: "darkness",
    statuses: {
      hp: 0,
      magicAtk: 169,
      magicDef: 0,
      physicalAtk: 169,
      physicalDef: 0,
    },
    imageUrl: host + "192.jpg",
    enhancementsNum: 2,
    equipCost: 27,
    specialEffects: [
      {
        rawText: "眠り無効化確率+80%",
      },
    ],
  },
  {
    id: 229,
    name: "宿世の燈火",
    rawName: "宿世の燈火",
    attribute: "fire",
    statuses: {
      hp: 0,
      magicAtk: 47,
      magicDef: 0,
      physicalAtk: 47,
      physicalDef: 0,
    },
    imageUrl: host + "199.jpg",
    enhancementsNum: 0,
    equipCost: 9,
    specialEffects: [
      {
        rawText: "行動不能無効化+40%",
      },
    ],
  },
  {
    id: 230,
    name: "宿世の燈火",
    rawName: "宿世の燈火+",
    attribute: "fire",
    statuses: {
      hp: 0,
      magicAtk: 108,
      magicDef: 0,
      physicalAtk: 108,
      physicalDef: 0,
    },
    imageUrl: host + "200.jpg",
    enhancementsNum: 1,
    equipCost: 18,
    specialEffects: [
      {
        rawText: "行動不能無効化+60%",
      },
    ],
  },
  {
    id: 231,
    name: "宿世の燈火",
    rawName: "宿世の燈火++",
    attribute: "fire",
    statuses: {
      hp: 0,
      magicAtk: 169,
      magicDef: 0,
      physicalAtk: 169,
      physicalDef: 0,
    },
    imageUrl: host + "201.jpg",
    enhancementsNum: 2,
    equipCost: 27,
    specialEffects: [
      {
        rawText: "行動不能無効化+80%",
      },
    ],
  },
  {
    id: 232,
    name: "紺碧の護剣",
    rawName: "紺碧の護剣",
    attribute: "wind",
    statuses: {
      hp: 0,
      magicAtk: 47,
      magicDef: 0,
      physicalAtk: 47,
      physicalDef: 0,
    },
    imageUrl: host + "219.jpg",
    enhancementsNum: 0,
    equipCost: 9,
    specialEffects: [
      {
        rawText: "攻撃低下デバフ無効化+30%",
      },
    ],
  },
  {
    id: 233,
    name: "紺碧の護剣",
    rawName: "紺碧の護剣+",
    attribute: "wind",
    statuses: {
      hp: 0,
      magicAtk: 108,
      magicDef: 0,
      physicalAtk: 108,
      physicalDef: 0,
    },
    imageUrl: host + "220.jpg",
    enhancementsNum: 1,
    equipCost: 18,
    specialEffects: [
      {
        rawText: "攻撃低下デバフ無効化+50%",
      },
    ],
  },
  {
    id: 234,
    name: "紺碧の護剣",
    rawName: "紺碧の護剣++",
    attribute: "wind",
    statuses: {
      hp: 0,
      magicAtk: 169,
      magicDef: 0,
      physicalAtk: 169,
      physicalDef: 0,
    },
    imageUrl: host + "221.jpg",
    enhancementsNum: 2,
    equipCost: 27,
    specialEffects: [
      {
        rawText: "攻撃低下デバフ無効化+70%",
      },
    ],
  },
  {
    id: 235,
    name: "黒後家蜘蛛の嘲笑",
    rawName: "黒後家蜘蛛の嘲笑",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 38,
      magicDef: 0,
      physicalAtk: 38,
      physicalDef: 0,
    },
    imageUrl: host + "228.jpg",
    enhancementsNum: 0,
    equipCost: 9,
    specialEffects: [
      {
        rawText: "防御・魔防低下デバフを20%の確率で無効",
      },
    ],
  },
  {
    id: 236,
    name: "黒後家蜘蛛の嘲笑",
    rawName: "黒後家蜘蛛の嘲笑+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 94,
      magicDef: 0,
      physicalAtk: 94,
      physicalDef: 0,
    },
    imageUrl: host + "229.jpg",
    enhancementsNum: 1,
    equipCost: 18,
    specialEffects: [
      {
        rawText: "防御・魔防低下デバフを35%の確率で無効",
      },
    ],
  },
  {
    id: 237,
    name: "黒後家蜘蛛の嘲笑",
    rawName: "黒後家蜘蛛の嘲笑++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 150,
      magicDef: 0,
      physicalAtk: 150,
      physicalDef: 0,
    },
    imageUrl: host + "230.jpg",
    enhancementsNum: 2,
    equipCost: 27,
    specialEffects: [
      {
        rawText: "防御・魔防低下デバフを50%の確率で無効",
      },
    ],
  },
  {
    id: 238,
    name: "鋼の剣",
    rawName: "鋼の剣",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 6,
      magicDef: 0,
      physicalAtk: 24,
      physicalDef: 0,
    },
    imageUrl: host + "7.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 239,
    name: "鋼の斧",
    rawName: "鋼の斧",
    attribute: "void",
    statuses: {
      hp: 30,
      magicAtk: 6,
      magicDef: 0,
      physicalAtk: 18,
      physicalDef: 0,
    },
    imageUrl: host + "8.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 240,
    name: "ワンド",
    rawName: "ワンド",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 24,
      magicDef: 0,
      physicalAtk: 6,
      physicalDef: 0,
    },
    imageUrl: host + "9.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 241,
    name: "魔術書",
    rawName: "魔術書",
    attribute: "void",
    statuses: {
      hp: 30,
      magicAtk: 18,
      magicDef: 0,
      physicalAtk: 6,
      physicalDef: 0,
    },
    imageUrl: host + "10.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 242,
    name: "クロスボウ",
    rawName: "クロスボウ",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 18,
      magicDef: 0,
      physicalAtk: 18,
      physicalDef: 0,
    },
    imageUrl: host + "11.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 243,
    name: "鎖のムチ",
    rawName: "鎖のムチ",
    attribute: "void",
    statuses: {
      hp: 30,
      magicAtk: 15,
      magicDef: 0,
      physicalAtk: 15,
      physicalDef: 0,
    },
    imageUrl: host + "12.jpg",
    enhancementsNum: 0,
    equipCost: 6,
    specialEffects: [],
  },
  {
    id: 244,
    name: "鋼の剣",
    rawName: "鋼の剣+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 10,
      magicDef: 0,
      physicalAtk: 40,
      physicalDef: 0,
    },
    imageUrl: host + "25.jpg",
    enhancementsNum: 1,
    equipCost: 8,
    specialEffects: [],
  },
  {
    id: 245,
    name: "鋼の斧",
    rawName: "鋼の斧+",
    attribute: "void",
    statuses: {
      hp: 50,
      magicAtk: 10,
      magicDef: 0,
      physicalAtk: 30,
      physicalDef: 0,
    },
    imageUrl: host + "26.jpg",
    enhancementsNum: 1,
    equipCost: 8,
    specialEffects: [],
  },
  {
    id: 246,
    name: "ワンド",
    rawName: "ワンド+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 40,
      magicDef: 0,
      physicalAtk: 10,
      physicalDef: 0,
    },
    imageUrl: host + "27.jpg",
    enhancementsNum: 1,
    equipCost: 8,
    specialEffects: [],
  },
  {
    id: 247,
    name: "魔術書",
    rawName: "魔術書+",
    attribute: "void",
    statuses: {
      hp: 50,
      magicAtk: 30,
      magicDef: 0,
      physicalAtk: 10,
      physicalDef: 0,
    },
    imageUrl: host + "28.jpg",
    enhancementsNum: 1,
    equipCost: 8,
    specialEffects: [],
  },
  {
    id: 248,
    name: "クロスボウ",
    rawName: "クロスボウ+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 30,
      magicDef: 0,
      physicalAtk: 30,
      physicalDef: 0,
    },
    imageUrl: host + "29.jpg",
    enhancementsNum: 1,
    equipCost: 8,
    specialEffects: [],
  },
  {
    id: 249,
    name: "鎖のムチ",
    rawName: "鎖のムチ+",
    attribute: "void",
    statuses: {
      hp: 50,
      magicAtk: 25,
      magicDef: 0,
      physicalAtk: 25,
      physicalDef: 0,
    },
    imageUrl: host + "30.jpg",
    enhancementsNum: 1,
    equipCost: 8,
    specialEffects: [],
  },
  {
    id: 250,
    name: "鋼の剣",
    rawName: "鋼の剣++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 14,
      magicDef: 0,
      physicalAtk: 56,
      physicalDef: 0,
    },
    imageUrl: host + "43.jpg",
    enhancementsNum: 2,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 251,
    name: "鋼の斧",
    rawName: "鋼の斧++",
    attribute: "void",
    statuses: {
      hp: 70,
      magicAtk: 14,
      magicDef: 0,
      physicalAtk: 42,
      physicalDef: 0,
    },
    imageUrl: host + "44.jpg",
    enhancementsNum: 2,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 252,
    name: "ワンド",
    rawName: "ワンド++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 56,
      magicDef: 0,
      physicalAtk: 14,
      physicalDef: 0,
    },
    imageUrl: host + "45.jpg",
    enhancementsNum: 2,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 253,
    name: "魔術書",
    rawName: "魔術書++",
    attribute: "void",
    statuses: {
      hp: 70,
      magicAtk: 42,
      magicDef: 0,
      physicalAtk: 14,
      physicalDef: 0,
    },
    imageUrl: host + "46.jpg",
    enhancementsNum: 2,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 254,
    name: "クロスボウ",
    rawName: "クロスボウ++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 42,
      magicDef: 0,
      physicalAtk: 42,
      physicalDef: 0,
    },
    imageUrl: host + "47.jpg",
    enhancementsNum: 2,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 255,
    name: "鎖のムチ",
    rawName: "鎖のムチ++",
    attribute: "void",
    statuses: {
      hp: 70,
      magicAtk: 35,
      magicDef: 0,
      physicalAtk: 35,
      physicalDef: 0,
    },
    imageUrl: host + "48.jpg",
    enhancementsNum: 2,
    equipCost: 10,
    specialEffects: [],
  },
  {
    id: 256,
    name: "銅の剣",
    rawName: "銅の剣",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 3,
      magicDef: 0,
      physicalAtk: 20,
      physicalDef: 0,
    },
    imageUrl: host + "1.jpg",
    enhancementsNum: 0,
    equipCost: 3,
    specialEffects: [],
  },
  {
    id: 257,
    name: "銅の斧",
    rawName: "銅の斧",
    attribute: "void",
    statuses: {
      hp: 15,
      magicAtk: 3,
      magicDef: 0,
      physicalAtk: 9,
      physicalDef: 0,
    },
    imageUrl: host + "2.jpg",
    enhancementsNum: 0,
    equipCost: 3,
    specialEffects: [],
  },
  {
    id: 258,
    name: "見習いステッキ",
    rawName: "見習いステッキ",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 12,
      magicDef: 0,
      physicalAtk: 3,
      physicalDef: 0,
    },
    imageUrl: host + "3.jpg",
    enhancementsNum: 0,
    equipCost: 3,
    specialEffects: [],
  },
  {
    id: 259,
    name: "本",
    rawName: "本",
    attribute: "void",
    statuses: {
      hp: 15,
      magicAtk: 9,
      magicDef: 0,
      physicalAtk: 3,
      physicalDef: 0,
    },
    imageUrl: host + "4.jpg",
    enhancementsNum: 0,
    equipCost: 3,
    specialEffects: [],
  },
  {
    id: 260,
    name: "弓",
    rawName: "弓",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 9,
      magicDef: 0,
      physicalAtk: 9,
      physicalDef: 0,
    },
    imageUrl: host + "5.jpg",
    enhancementsNum: 0,
    equipCost: 3,
    specialEffects: [],
  },
  {
    id: 261,
    name: "革のムチ",
    rawName: "革のムチ",
    attribute: "void",
    statuses: {
      hp: 15,
      magicAtk: 8,
      magicDef: 0,
      physicalAtk: 8,
      physicalDef: 0,
    },
    imageUrl: host + "6.jpg",
    enhancementsNum: 0,
    equipCost: 3,
    specialEffects: [],
  },
  {
    id: 262,
    name: "銅の剣",
    rawName: "銅の剣+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 7,
      magicDef: 0,
      physicalAtk: 26,
      physicalDef: 0,
    },
    imageUrl: host + "19.jpg",
    enhancementsNum: 1,
    equipCost: 5,
    specialEffects: [],
  },
  {
    id: 263,
    name: "銅の斧",
    rawName: "銅の斧+",
    attribute: "void",
    statuses: {
      hp: 33,
      magicAtk: 7,
      magicDef: 0,
      physicalAtk: 20,
      physicalDef: 0,
    },
    imageUrl: host + "20.jpg",
    enhancementsNum: 1,
    equipCost: 5,
    specialEffects: [],
  },
  {
    id: 264,
    name: "見習いステッキ",
    rawName: "見習いステッキ+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 26,
      magicDef: 0,
      physicalAtk: 7,
      physicalDef: 0,
    },
    imageUrl: host + "21.jpg",
    enhancementsNum: 1,
    equipCost: 5,
    specialEffects: [],
  },
  {
    id: 265,
    name: "本",
    rawName: "本+",
    attribute: "void",
    statuses: {
      hp: 33,
      magicAtk: 20,
      magicDef: 0,
      physicalAtk: 7,
      physicalDef: 0,
    },
    imageUrl: host + "22.jpg",
    enhancementsNum: 1,
    equipCost: 5,
    specialEffects: [],
  },
  {
    id: 266,
    name: "弓",
    rawName: "弓+",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 20,
      magicDef: 0,
      physicalAtk: 20,
      physicalDef: 0,
    },
    imageUrl: host + "23.jpg",
    enhancementsNum: 1,
    equipCost: 5,
    specialEffects: [],
  },
  {
    id: 267,
    name: "革のムチ",
    rawName: "革のムチ+",
    attribute: "void",
    statuses: {
      hp: 33,
      magicAtk: 17,
      magicDef: 0,
      physicalAtk: 17,
      physicalDef: 0,
    },
    imageUrl: host + "24.jpg",
    enhancementsNum: 1,
    equipCost: 5,
    specialEffects: [],
  },
  {
    id: 268,
    name: "銅の剣",
    rawName: "銅の剣++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 10,
      magicDef: 0,
      physicalAtk: 41,
      physicalDef: 0,
    },
    imageUrl: host + "37.jpg",
    enhancementsNum: 2,
    equipCost: 7,
    specialEffects: [],
  },
  {
    id: 269,
    name: "銅の斧",
    rawName: "銅の斧++",
    attribute: "void",
    statuses: {
      hp: 51,
      magicAtk: 10,
      magicDef: 0,
      physicalAtk: 31,
      physicalDef: 0,
    },
    imageUrl: host + "38.jpg",
    enhancementsNum: 2,
    equipCost: 7,
    specialEffects: [],
  },
  {
    id: 270,
    name: "見習いステッキ",
    rawName: "見習いステッキ++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 41,
      magicDef: 0,
      physicalAtk: 10,
      physicalDef: 0,
    },
    imageUrl: host + "39.jpg",
    enhancementsNum: 2,
    equipCost: 7,
    specialEffects: [],
  },
  {
    id: 271,
    name: "本",
    rawName: "本++",
    attribute: "void",
    statuses: {
      hp: 51,
      magicAtk: 31,
      magicDef: 0,
      physicalAtk: 10,
      physicalDef: 0,
    },
    imageUrl: host + "40.jpg",
    enhancementsNum: 2,
    equipCost: 7,
    specialEffects: [],
  },
  {
    id: 272,
    name: "弓",
    rawName: "弓++",
    attribute: "void",
    statuses: {
      hp: 0,
      magicAtk: 31,
      magicDef: 0,
      physicalAtk: 31,
      physicalDef: 0,
    },
    imageUrl: host + "41.jpg",
    enhancementsNum: 2,
    equipCost: 7,
    specialEffects: [],
  },
  {
    id: 273,
    name: "革のムチ",
    rawName: "革のムチ++",
    attribute: "void",
    statuses: {
      hp: 51,
      magicAtk: 26,
      magicDef: 0,
      physicalAtk: 26,
      physicalDef: 0,
    },
    imageUrl: host + "42.jpg",
    enhancementsNum: 2,
    equipCost: 7,
    specialEffects: [],
  },
] as CastAny
